### ISSUE TITLE
Some lighting presets may be missing important key:value

### ISSUE THREAD

**Issue by PitchBright** [webbukkit/DynmapCore#69] opened 2016-09-11 20:12 UTC
A friend noticed that he couldn't get "brightnight-smooth" lighting preset to work for him. He wanted to have a night-time version of the map.

I also tried it and couldn't get it to work. I then tried all the other night variants, and they wouldn't work either. The only way I was able to get a night version of the map, is when I used a day-night lighting preset, that would allow the map to switch from day to night tiles.

I started poking around code on git and I noticed this line:

https://github.com/webbukkit/DynmapCore/blob/master/src/main/java/org/dynmap/hdmap/ShadowHDLighting.java#L39

That made me want to try editing the configuration.txt file and change the following line from true to false, as a test:
`use-brightness-table: false`

That seemed to do the trick, all the night lighting presets worked.

Not understanding exactly what that setting does, I was hesitant to just change it and leave it, thinking that it may affect other maps, without me noticing the change right away. So I then decided to try editing lighting.txt file, and included 

`use-brightness-table: false`

... on all the night view presets. That also worked.

From there I reverted the lighting.txt file, knowing that the file really shouldn't be edited (in case of future update changes)... and I set about adding a night-time preset to the custom-lighting.txt. Again, that also worked.

This leads me to think that maybe you forgot to add that line to the night-view presets in the lighting.txt preset file, and that there is no problems/bugs in the actual code. Since, I'm assuming, configuration.txt should probably leave that value set to true.

FWIW, I didn't test all versions of Dynmap. I've only tried this on the Forge version, so I'm not sure if this problem would show up for other users, using other versions, but I'm guessing it might.

**Comment by Xylios** [comment] 2017-04-17 03:15
Isolated the problem to these lines of code: https://github.com/webbukkit/DynmapCore/blob/900bfbd469979d044f45387d54f3b056dbf41c6d/src/main/java/org/dynmap/hdmap/ShadowHDLighting.java#L38-L41
It forces ambient light to be 15 (daylight) when use-brightness-table is true.
Looks like it got fixed with a workaround for night-and-day in the past but not for the other night lighting presets.
The reason why it ignores the ambient light setting when use-brightness-table is true isn't really clear to me either, since use-brightness-table is set to true by default, and as a result the ambient light setting will be ignored in every lighting preset by default too, which doesn't seem like expected behavior and will confuse users, like it does now.

**Comment by mikeprimm** [comment] 2018-02-15 04:33
Just fixed this in current code (v2.6-alpha-2 and v3.0-alpha-1)

**Closed by mikeprimm** 2018-02-15 04:33 UTC
